name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: zol-test-image
  DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        image_tag="$(git rev-parse --short HEAD)"
        docker build . --file Dockerfile --tag ${DOCKER_USER}/${IMAGE_NAME}:${image_tag}
    
    - name: Login to Docker Hub
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    - name: Push to Docker Hub
      run: |
        docker push ${DOCKER_USER}/${IMAGE_NAME}

